### PR TITLE
Move to CircleCI

### PR DESCRIPTION
**Pull request by ShaishavGandhi**
Still WIP
Ref #220

### CODE REVIEW

**Comment by ZacSweers** [comment]
Does Uber have an FTL account that we can use for instrumentation tests?

**Comment by ShaishavGandhi** [comment]
I saw some StackOverflow where they were able to run espresso tests on emulator without FTL. Seeing if that works out otherwise might have to go the FTL path.

**Comment by ShaishavGandhi** [comment]
Have been able to get the emulator tests running! 
Going to take a look at uploading snapshots and then we can phase out Travis.

**Comment by ShaishavGandhi** [comment]
I think I'm going to continue this on my fork and come back when I have something that works.

**Pull request closed without merging**
