### PR TITLE
Downgrade Gradle wrapper to 5.6.4

### LINKED ISSUE #400: Lower gradle version back to 5.x
AARs don't seem to be consumable when built with 6.x is: https://issuetracker.google.com/issues/144240061

### PR DESCRIPTION
**Pull request by friederbluemle**
Downgrades Gradle to the latest 5.x release.

Fixes #400

### CODE REVIEW

**Comment by ZacSweers** [comment]
Did this not make any changes to the gradle wrapper jar?

**Comment by friederbluemle** [comment]
The update to `gradle-wrapper.properties` was done through the Gradle `wrapper` task (not by manually modifying the file). Since there was no change to the jar file I assume no changes.

For several version now, Gradle has fixed the ever changing jar file issue (likely caused by some file that had only a text timestamp updated). The contents of the jar file (just like the wrapper scripts) should only change very rarely.

**Comment by ZacSweers** [comment]
I get stale state locally when I do this.

image


I'll take this over in a separate PR anyway as I want to add a validation layer from this https://gist.github.com/ZacSweers/91597b19744f5fe314313ae9b11d6879

**Comment by ZacSweers** [comment]
Continued in #403

**Comment by friederbluemle** [comment]
What do you mean by "stale state locally" - Which command did you run before `git status`?

**Comment by ZacSweers** [comment]
The wrapper task _only_ updates the properties file. Subsequent Gradle runs
actually perform the bootstrapping, it’s weird

**Pull request closed without merging**
