### PR TITLE
Add gradle wrapper validation

### PR DESCRIPTION
**Pull request by ZacSweers**
~~This downgrades gradle back to 5.6.3 (#400) and also~~ adds a validation script from  https://github.com/ZacSweers/check-gradle-checksums to make accepting new jars safer

### CODE REVIEW

**Comment by ZacSweers** [comment]
Apparently this command isn't installed, nor is this properly failing the build 🤔. Needs more work

```
Run ./checkGradleChecksum.sh
Checking Gradle wrapper jar for version: 5.6.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100    64  100    64    0     0    581      0 --:--:-- --:--:-- --:--:--   581
./checkGradleChecksum.sh: line 67: sha256sum: command not found
Gradle wrapper failed checksum verification. Please investigate.
```

**Comment by ZacSweers** [comment]
Script updated to properly fail the build now, also requested sha256sum to be added to macOS on GH actions: https://github.com/actions/virtual-environments/issues/90

**Comment by imbsky** [comment]
Try this.

```yml
- name: Install coreutils for macOS
  run: brew install coreutils
```

or

```yml
- name: Install coreutils for macOS
  if: matrix.os == 'macOS-latest'
  run: brew install coreutils
```

**Comment by imbsky** [comment]
```
~
❯ sha256sum --version
sha256sum (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
```

**Comment by ZacSweers** [comment]
Thanks! We'll use that as a workaround in the meantime.

**Comment by imbsky** [comment]
I'm glad you seem to have avoided the issue!

**Comment by ZacSweers** [comment]
Going to actually raise this back up to 6.0 as this appears to have been a different issue in the reporting issue. Will make this PR just about validation

**Comment by ZacSweers** [comment]
Going ahead and merging this while Uber figures out whether or not they want to pay their GitHub bills

**Pull request merged**
